#!/usr/bin/env node

/**
 * @file
 * Use this script to copy specific files from node_modules
 * to the src directory before running Eleventy.
 *
 * Tbh, I'm worried that this might necessitate using a bundler
 * to deal with modules in third-party scripts.
 * So, **AVOID USING THIS AS MUCH AS POSSIBLE!!!**
 *
 * For files in node_modules that are preoptimized,
 * use Eleventy's passthroughcopy instead.
 * Only use this to copy things that are not preoptimized
 * that you need to transform/optimize **in** templates,
 * e.g. by inlining them.
 *
 * Anyway, **don't forget to git ignore the copied files!**
 */

const fs = require("fs/promises")

async function main() {
  const stuffToCopy = {
    "node_modules/lite-youtube-embed/src/lite-yt-embed.css":
      "src/_includes/css/lite-yt-embed.css",
    "node_modules/lite-youtube-embed/src/lite-yt-embed.js":
      "src/_includes/js/lite-yt-embed.js",
  }

  for (const [src, dest] of Object.entries(stuffToCopy)) {
    await fs.copyFile(src, dest)
    console.log(`Copied ${src} to ${dest}.`)
  }
}

main()
