#!/usr/bin/env bash

# Use this script to convert images to WebP format.

dest='public/assets/images/'

read -r -d '' HELP << EOM
Usage:
  to-webp [-h|--help]
  to-webp <path|glob> [--clean]

Convert images to WebP format and save them to "$dest".

Options:
  -h, --help  Show this message.
  --clean     Delete the source images after converting.

Examples:
  to-webp "image.png"
  to-webp "public/assets/*.jpg" --clean
EOM

if [ -z "$1" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]
then
  echo "$HELP" && exit 0
fi

npx imagemin "$1" --out-dir="$dest" --plugin=webp

if [ "$2" = "--clean" ]
then
  # Let the shell expand the (maybe) glob;
  # rm accepts multiple paths but not globs.
  rm --verbose $1
fi
